# Generated by Django 4.0.3 on 2022-04-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('video_link', models.IntegerField(blank=True, default=0)),
                ('whatsap', models.CharField(blank=True, max_length=300)),
                ('youtube', models.CharField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=600)),
                ('status', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=600)),
                ('position', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('sublect', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='email',
            field=models.EmailField(blank=True, max_length=300),
        ),
    ]
