# Generated by Django 4.0.3 on 2022-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vacancy_staff_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='video_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
