# Generated by Django 4.0.3 on 2022-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_filial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prize',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
